version: '3.1'
services:
  consul:
    image: 'consul:latest'
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
      4taldea_lb7_network:
        ipv4_address: '${CONSUL_HOST}'
  delivery:
    hostname: delivery
    build: ./delivery
    volumes:
      - './delivery/app:/app'
    expose:
      - '${DELIVERY_PORT}'
    environment:
      GUNICORN_PORT: '${DELIVERY_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CONSUL_HOST: '${CONSUL_HOST}'
      DELIVERY_NAME: '${DELIVERY_NAME}'
      DELIVERY_IP: '${DELIVERY_IP}'
    networks:
      4taldea_lb7_network:
        ipv4_address: '${DELIVERY_IP}'
    restart: unless-stopped
  order:
    hostname: order
    build: ./order
    volumes:
      - './order/app:/app'
    expose:
      - '${ORDER_PORT}'
    environment:
      GUNICORN_PORT: '${ORDER_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CONSUL_HOST: '${CONSUL_HOST}'
      ORDER_NAME: '${ORDER_NAME}'
      ORDER_IP: '${ORDER_IP}'
    networks:
      4taldea_lb7_network:
        ipv4_address: '${ORDER_IP}'
    restart: unless-stopped
  machine:
    hostname: machine
    build: ./machine
    volumes:
      - './machine/app:/app'
    expose:
      - '${MACHINE_PORT}'
    environment:
      GUNICORN_PORT: '${MACHINE_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CONSUL_HOST: '${CONSUL_HOST}'
      MACHINE_NAME: '${MACHINE_NAME}'
      MACHINE_IP: '${MACHINE_IP}'
    networks:
      4taldea_lb7_network:
        ipv4_address: '${MACHINE_IP}'
    restart: unless-stopped
  payment:
    hostname: payment
    build: ./payment
    volumes:
      - './payment/app:/app'
    expose:
      - '${PAYMENT_PORT}'
    environment:
      GUNICORN_PORT: '${PAYMENT_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CONSUL_HOST: '${CONSUL_HOST}'
      PAYMENT_NAME: '${PAYMENT_NAME}'
      PAYMENT_IP: '${PAYMENT_IP}'
    networks:
      4taldea_lb7_network:
        ipv4_address: '${PAYMENT_IP}'
    restart: unless-stopped
  client:
    hostname: client
    build: ./client
    volumes:
      - './client/app:/app'
    expose:
      - '${CLIENT_PORT}'
    environment:
      GUNICORN_PORT: '${CLIENT_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CONSUL_HOST: '${CONSUL_HOST}'
      CLIENT_NAME: '${CLIENT_NAME}'
      CLIENT_IP: '${CLIENT_IP}'
    networks:
      4taldea_lb7_network:
        ipv4_address: '${CLIENT_IP}'
    restart: unless-stopped
    depends_on:
      - delivery
      - payment
      - order
      - machine

  log:
    hostname: log
    build: ./log
    volumes:
      - './log/app:/app'
    expose:
      - '${LOG_PORT}'
    environment:
      GUNICORN_PORT: '${LOG_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CONSUL_HOST: '${CONSUL_HOST}'
      LOG_NAME: '${LOG_NAME}'
      LOG_IP: '${LOG_IP}'
    networks:
      4taldea_lb7_network:
        ipv4_address: '${LOG_IP}'
    restart: unless-stopped
networks:
  4taldea_lb7_network:
    external: true

